name: 'url-extractor'
description: 'URL Extractor'
author: 'PackedTide'
inputs:
  body:
    required: true
    description: 'text to parse'
  pattern:
    required: true
    description: 'url pattern'
    default: 'https?:'
runs:
  using: 'node12'
  main: 'dist/index.js'
